import { EventMaster } from '../types';

export const OFFICIAL_EVENTS: EventMaster[] = [
  // Technical Events (7)
  {
    eventId: 'TE01',
    title: 'Paper Presentation',
    category: 'Technical',
    type: 'Team',
    teamSize: '2-3 Members',
    venue: 'Seminar Hall A (Block 2)',
    startTime: '10:00 AM',
    endTime: '01:00 PM',
  },
  {
    eventId: 'TE02',
    title: 'Business Battle',
    category: 'Technical',
    type: 'Team',
    teamSize: '2-4 Members',
    venue: 'MBA Boardroom (Block 1)',
    startTime: '10:30 AM',
    endTime: '01:30 PM',
  },
  {
    eventId: 'TE03',
    title: 'Mind Sparks',
    category: 'Technical',
    type: 'Individual',
    venue: 'Computing Lab 1 (Block 3)',
    startTime: '11:00 AM',
    endTime: '12:30 PM',
  },
  {
    eventId: 'TE04',
    title: 'EditoMania',
    category: 'Technical',
    type: 'Individual',
    venue: 'Multimedia Lab (Block 3)',
    startTime: '11:30 AM',
    endTime: '01:30 PM',
  },
  {
    eventId: 'TE05',
    title: 'Lego Build with AI',
    category: 'Technical',
    type: 'Team',
    teamSize: '2-3 Members',
    venue: 'Robotics & AI Center',
    startTime: '10:00 AM',
    endTime: '01:00 PM',
  },
  {
    eventId: 'TE06',
    title: 'Cyber Investigation',
    category: 'Technical',
    type: 'Team',
    teamSize: '2 Members',
    venue: 'Cyber Security Lab (Block 2)',
    startTime: '10:30 AM',
    endTime: '01:00 PM',
  },
  {
    eventId: 'TE07',
    title: 'Code Red',
    category: 'Technical',
    type: 'Individual',
    venue: 'Advanced Programming Lab',
    startTime: '11:00 AM',
    endTime: '01:00 PM',
  },

  // Non-Technical Events (6)
  {
    eventId: 'NT01',
    title: 'Start Music',
    category: 'Non-Technical',
    type: 'Team',
    teamSize: '2-4 Members',
    venue: 'Auditorium Stage',
    startTime: '01:30 PM',
    endTime: '03:30 PM',
  },
  {
    eventId: 'NT02',
    title: 'Indo Japanese Game',
    category: 'Non-Technical',
    type: 'Individual',
    venue: 'Indoor Sports Arena',
    startTime: '02:00 PM',
    endTime: '03:30 PM',
  },
  {
    eventId: 'NT03',
    title: 'IPL Auction',
    category: 'Non-Technical',
    type: 'Team',
    teamSize: '3-4 Members',
    venue: 'Mini Auditorium',
    startTime: '01:30 PM',
    endTime: '04:00 PM',
  },
  {
    eventId: 'NT04',
    title: 'Meme & Adzap',
    category: 'Non-Technical',
    type: 'Team',
    teamSize: '2-4 Members',
    venue: 'Seminar Hall B',
    startTime: '02:00 PM',
    endTime: '03:45 PM',
  },
  {
    eventId: 'NT05',
    title: 'Cinematography',
    category: 'Non-Technical',
    type: 'Individual',
    venue: 'Media Center',
    startTime: '01:30 PM',
    endTime: '03:30 PM',
  },
  {
    eventId: 'NT06',
    title: 'Box Cricket',
    category: 'Non-Technical',
    type: 'Team',
    teamSize: '5-6 Members',
    venue: 'Sports Ground Turf',
    startTime: '01:00 PM',
    endTime: '04:00 PM',
  },

  // Special Events (2)
  {
    eventId: 'SP01',
    title: 'Workshop & AI Hack',
    category: 'Special',
    type: 'Individual',
    venue: 'Grand Innovation Hall',
    startTime: '09:30 AM',
    endTime: '01:00 PM',
  },
  {
    eventId: 'SP02',
    title: 'Tech Symposium Grand Challenge',
    category: 'Special',
    type: 'Team',
    teamSize: '2-4 Members',
    venue: 'Main Auditorium',
    startTime: '02:30 PM',
    endTime: '04:30 PM',
  },
];

export const getEventById = (id: string): EventMaster | undefined => {
  return OFFICIAL_EVENTS.find((e) => e.eventId.toUpperCase() === id.toUpperCase());
};
